
name: Create crate dist
on:
  push:
    tags:
      - '**'

jobs:
  crate-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create crate dist
        uses: projg2/crate-dist-action@v1
        with:
          directories: cskk
          dist-filename: cskk-3.1.5-crates.tar.xz
          run-cargo-update: false

